"""Gemini embedding gateway."""

import asyncio

from google import genai
from google.genai import types

from app.config.settings import Settings
from app.core.exceptions import ProviderError, ProviderTimeoutError
from app.providers.embedding.base import EmbeddingGateway


class GeminiEmbeddingGateway(EmbeddingGateway):
    """Batch embeddings generated by Gemini's async SDK client."""

    def __init__(self, config: Settings) -> None:
        if not config.GEMINI_API_KEY:
            raise ProviderError("GEMINI_API_KEY is required for embeddings.")
        self._client = genai.Client(api_key=config.GEMINI_API_KEY)
        self.model_name = config.GEMINI_EMBEDDING_MODEL
        self.dimensions = config.GEMINI_EMBEDDING_DIMENSIONS
        self._timeout = config.GEMINI_TIMEOUT_SECONDS
        self._retries = config.GEMINI_MAX_RETRIES

    async def embed(self, texts: list[str]) -> list[list[float]]:
        """Embed text in bounded batches while preserving source order."""
        if not texts:
            return []
        vectors: list[list[float]] = []
        for start in range(0, len(texts), 100):
            vectors.extend(await self._embed_batch(texts[start : start + 100]))
        return vectors

    async def _embed_batch(self, texts: list[str]) -> list[list[float]]:
        for attempt in range(self._retries + 1):
            try:
                response = await asyncio.wait_for(
                    self._client.aio.models.embed_content(
                        model=self.model_name,
                        contents=texts,
                        config=types.EmbedContentConfig(output_dimensionality=self.dimensions),
                    ),
                    timeout=self._timeout,
                )
                return [list(item.values) for item in response.embeddings]
            except TimeoutError as exc:
                if attempt == self._retries:
                    raise ProviderTimeoutError() from exc
            except Exception as exc:
                if attempt == self._retries:
                    raise ProviderError("Gemini embedding request failed.") from exc
            await asyncio.sleep(2**attempt)
        raise ProviderError("Gemini embedding request failed.")
