"""OpenRouter embedding gateway."""

import asyncio
from typing import Any

import httpx

from app.config.settings import Settings
from app.core.exceptions import ProviderError, ProviderTimeoutError
from app.providers.embedding.base import EmbeddingGateway


class OpenRouterEmbeddingGateway(EmbeddingGateway):
    """Batch embeddings generated by OpenRouter."""

    def __init__(self, config: Settings) -> None:
        if not config.OPENROUTER_API_KEY:
            raise ProviderError("OPENROUTER_API_KEY is required for embeddings.")
        self.api_key = config.OPENROUTER_API_KEY
        self.base_url = config.OPENROUTER_BASE_URL.rstrip("/")
        self.model_name = config.OPENROUTER_EMBEDDING_MODEL
        self.dimensions = config.OPENROUTER_EMBEDDING_DIMENSIONS
        self._timeout = config.GEMINI_TIMEOUT_SECONDS
        self._retries = config.GEMINI_MAX_RETRIES

    async def embed(self, inputs: list[str | list[dict[str, Any]]]) -> list[list[float]]:
        """Embed text or multimodal content in bounded batches while preserving source order."""
        if not inputs:
            return []
        vectors: list[list[float]] = []
        # OpenRouter/OpenAI API typically supports batching, but for multimodal we might need smaller batches
        # due to payload size. Let's use a batch size of 20 to be safe with images.
        batch_size = 20
        for start in range(0, len(inputs), batch_size):
            vectors.extend(await self._embed_batch(inputs[start : start + batch_size]))
        return vectors

    async def _embed_batch(self, inputs: list[str | list[dict[str, Any]]]) -> list[list[float]]:
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "HTTP-Referer": "http://localhost:5173",  # Best practice for OpenRouter
            "X-Title": "Enterprise AI Knowledge Platform",
        }
        formatted_inputs = []
        has_multimodal = any(isinstance(item, list) for item in inputs)
        for item in inputs:
            if isinstance(item, list):
                formatted_inputs.append({"content": item})
            elif has_multimodal:
                formatted_inputs.append({"content": [{"type": "text", "text": item}]})
            else:
                formatted_inputs.append(item)

        payload = {
            "model": self.model_name,
            "input": formatted_inputs
        }
        
        async with httpx.AsyncClient(timeout=self._timeout) as client:
            for attempt in range(self._retries + 1):
                try:
                    response = await client.post(
                        f"{self.base_url}/embeddings",
                        headers=headers,
                        json=payload,
                    )
                    
                    if response.status_code == 429:
                        # Rate limited
                        if attempt == self._retries:
                            raise ProviderError("OpenRouter rate limit exceeded.")
                        await asyncio.sleep(2 ** attempt)
                        continue
                        
                    response.raise_for_status()
                    data = response.json()
                    
                    if "data" not in data:
                        raise ProviderError(f"Unexpected OpenRouter response: {data}")
                        
                    # Extract embeddings maintaining the original order
                    embeddings = [item["embedding"] for item in sorted(data["data"], key=lambda x: x["index"])]
                    
                    # Validate dimensions
                    if embeddings and len(embeddings[0]) != self.dimensions:
                        raise ProviderError(f"Expected {self.dimensions} dimensions, got {len(embeddings[0])}.")
                        
                    return embeddings
                except httpx.TimeoutException as exc:
                    if attempt == self._retries:
                        raise ProviderTimeoutError() from exc
                except ProviderError:
                    raise
                except httpx.HTTPStatusError as exc:
                    if attempt == self._retries:
                        raise ProviderError(f"OpenRouter embedding request failed: {exc.response.text}") from exc
                except Exception as exc:
                    if attempt == self._retries:
                        raise ProviderError("OpenRouter embedding request failed.") from exc
                await asyncio.sleep(2 ** attempt)
            
        raise ProviderError("OpenRouter embedding request failed.")
